name: min2_sports_today
description: Love sports
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: "1.0.0"
  flutter_launcher_icons: ^0.8.1
  provider: ^4.3.2+4


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_launcher.png"
  adaptive_icon_background: "#212121"
  adaptive_icon_foreground: "assets/icons/ic_launcher.png"



flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Regular
      fonts:
        - asset: assets/fonts/HachiMaruPop-Regular.ttf
    - family: Bold
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
